//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinker_quest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DannyD
    {
        public int IdContract { get; set; }
        public string NumberContract { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public string DataPostawki { get; set; }
        public string Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
