//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinker_quest
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdProdukts
    {
        public int IdGoods { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string Remove { get; set; }
    }
}
